spring.application.name=resource-lending-api
spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.data.rest.basePath=/api
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
api.security.token.secret=${JWT_SECRET}
api.security.email-confirmation-token=${EMAIL_CONFIRMATION_TOKEN}
