CREATE TABLE cliente (
    codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_cliente VARCHAR(31) NOT NULL,
    nome VARCHAR(255),
    idade INTEGER,
    telefone VARCHAR(255),
    endereco VARCHAR(255),
    CONSTRAINT ck_cliente_tipo
        CHECK (tipo_cliente IN ('ALUNO', 'PAI_DE_ALUNO')),
    CONSTRAINT ck_cliente_idade
        CHECK (idade IS NULL OR idade >= 0)
);

CREATE TABLE aluno (
    codigo BIGINT PRIMARY KEY,
    CONSTRAINT fk_aluno_cliente
        FOREIGN KEY (codigo) REFERENCES cliente (codigo) ON DELETE CASCADE
);

CREATE TABLE pai_de_aluno (
    codigo BIGINT PRIMARY KEY,
    CONSTRAINT fk_pai_de_aluno_cliente
        FOREIGN KEY (codigo) REFERENCES cliente (codigo) ON DELETE CASCADE
);

CREATE TABLE exemplar (
    codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_exemplar VARCHAR(31) NOT NULL,
    nome VARCHAR(255),
    CONSTRAINT ck_exemplar_tipo
        CHECK (tipo_exemplar IN ('Livro', 'Artigo', 'Periodico'))
);

CREATE TABLE livro (
    codigo BIGINT PRIMARY KEY,
    autor VARCHAR(255),
    editora VARCHAR(255),
    edicao INTEGER,
    CONSTRAINT fk_livro_exemplar
        FOREIGN KEY (codigo) REFERENCES exemplar (codigo) ON DELETE CASCADE,
    CONSTRAINT ck_livro_edicao
        CHECK (edicao IS NULL OR edicao > 0)
);

CREATE TABLE artigo (
    codigo BIGINT PRIMARY KEY,
    autor VARCHAR(255),
    CONSTRAINT fk_artigo_exemplar
        FOREIGN KEY (codigo) REFERENCES exemplar (codigo) ON DELETE CASCADE
);

CREATE TABLE periodico (
    codigo BIGINT PRIMARY KEY,
    editora VARCHAR(255),
    CONSTRAINT fk_periodico_exemplar
        FOREIGN KEY (codigo) REFERENCES exemplar (codigo) ON DELETE CASCADE
);

CREATE TABLE emprestimo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_emprestimo DATE,
    data_devolucao DATE,
    cliente_id BIGINT,
    exemplar_id BIGINT,
    CONSTRAINT fk_emprestimo_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente (codigo),
    CONSTRAINT fk_emprestimo_exemplar
        FOREIGN KEY (exemplar_id) REFERENCES exemplar (codigo),
    CONSTRAINT ck_emprestimo_datas
        CHECK (
            data_emprestimo IS NULL
            OR data_devolucao IS NULL
            OR data_devolucao >= data_emprestimo
        )
);

CREATE INDEX idx_emprestimo_cliente_id ON emprestimo (cliente_id);
CREATE INDEX idx_emprestimo_exemplar_id ON emprestimo (exemplar_id);

CREATE TABLE perfis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    CONSTRAINT uk_perfis_nome UNIQUE (nome)
);

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    sobrenome VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    is_confirmado BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_usuarios_email UNIQUE (email)
);

CREATE TABLE usuarios_perfis (
    usuarios_id BIGINT NOT NULL,
    perfis_id BIGINT NOT NULL,
    CONSTRAINT pk_usuarios_perfis PRIMARY KEY (usuarios_id, perfis_id),
    CONSTRAINT fk_usuarios_perfis_usuario
        FOREIGN KEY (usuarios_id) REFERENCES usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_usuarios_perfis_perfil
        FOREIGN KEY (perfis_id) REFERENCES perfis (id) ON DELETE CASCADE
);

CREATE INDEX idx_usuarios_perfis_perfis_id ON usuarios_perfis (perfis_id);
